import type { Kpi, Role, Notification } from "@/lib/types";

export const kpis: Record<Role, Kpi[]> = {
  CEO: [
    {
      id: "ceo-1",
      title: "Annual Recurring Revenue (ARR)",
      value: "$11.2M",
      change: "+8.1%",
      changeType: "increase",
      status: "at-risk",
      description: "vs. previous year",
      icon: "DollarSign",
      chartType: "line",
      trendData: [
        { month: "Jan", value: 8.2 },
        { month: "Feb", value: 9.1 },
        { month: "Mar", value: 10.5 },
        { month: "Apr", value: 10.8 },
        { month: "May", value: 11.0 },
        { month: "Jun", value: 11.2 },
      ],
      comments: [
        {
          id: 1,
          author: "Alex G.",
          avatar: "https://picsum.photos/seed/1/32/32",
          text: "Growth is slowing. What's the plan to re-accelerate?",
          timestamp: "3h ago",
        },
      ],
    },
    {
      id: "ceo-2",
      title: "Customer Acquisition Cost (CAC)",
      value: "$295",
      change: "+12.5%",
      changeType: "increase",
      status: "off-track",
      description: "vs. previous quarter",
      icon: "Users",
      chartType: "line",
      trendData: [
        { month: "Jan", value: 240 },
        { month: "Feb", value: 255 },
        { month: "Mar", value: 265 },
        { month: "Apr", value: 280 },
        { month: "May", value: 290 },
        { month: "Jun", value: 295 },
      ],
      comments: [
        {
          id: 1,
          author: "Sarah K.",
          avatar: "https://picsum.photos/seed/2/32/32",
          text: "This is alarming. Marketing needs to investigate ad spend efficiency.",
          timestamp: "5h ago",
        },
      ],
    },
    {
      id: "ceo-3",
      title: "Customer Lifetime Value (CLV)",
      value: "$4,650",
      change: "-3.1%",
      changeType: "decrease",
      status: "at-risk",
      description: "vs. previous year",
      icon: "HeartHandshake",
      chartType: "line",
      trendData: [
        { month: "Jan", value: 4800 },
        { month: "Feb", value: 4780 },
        { month: "Mar", value: 4750 },
        { month: "Apr", value: 4700 },
        { month: "May", value: 4680 },
        { month: "Jun", value: 4650 },
      ],
      comments: [],
    },
    {
      id: "ceo-4",
      title: "Market Share",
      value: "25%",
      change: "+3.0%",
      changeType: "increase",
      status: "on-track",
      description: "vs. previous quarter",
      icon: "Briefcase",
      chartType: "bar",
      trendData: [
        { month: "Jan", value: 20 },
        { month: "Feb", value: 21 },
        { month: "Mar", value: 22 },
        { month: "Apr", value: 23 },
        { month: "May", value: 24 },
        { month: "Jun", value: 25 },
      ],
      comments: [
        {
          id: 1,
          author: "Alex G.",
          avatar: "https://picsum.photos/seed/1/32/32",
          text: "Aggressive push into the new segment is paying off.",
          timestamp: "1d ago",
        },
      ],
    },
  ],
  Manager: [
    {
      id: "mgr-1",
      title: "Team Velocity",
      value: "35 points",
      change: "-15%",
      changeType: "decrease",
      status: "at-risk",
      description: "vs. last sprint",
      icon: "Zap",
      chartType: "bar",
      trendData: [
        { month: "Sprint 1", value: 45 },
        { month: "Sprint 2", value: 42 },
        { month: "Sprint 3", value: 38 },
        { month: "Sprint 4", value: 35 },
      ],
      comments: [
        {
          id: 1,
          author: "You (Manager)",
          avatar: "https://picsum.photos/seed/3/32/32",
          text: "Team, we need to discuss the blockers from the last sprint.",
          timestamp: "2h ago",
        },
      ],
    },
    {
      id: "mgr-2",
      title: "Average Ticket Resolution Time",
      value: "3.1 hours",
      change: "+24%",
      changeType: "increase",
      status: "off-track",
      description: "vs. last month",
      icon: "Activity",
      chartType: "line",
      trendData: [
        { month: "Mar", value: 2.5 },
        { month: "Apr", value: 2.8 },
        { month: "May", value: 2.9 },
        { month: "Jun", value: 3.1 },
      ],
      comments: [],
    },
    {
      id: "mgr-3",
      title: "Q3 Project Completion Rate",
      value: "92%",
      change: "+2%",
      changeType: "increase",
      status: "on-track",
      description: "Target: 90%",
      icon: "Target",
      chartType: "bar",
      trendData: [
        { month: "Task 1", value: 100 },
        { month: "Task 2", value: 95 },
        { month: "Task 3", value: 88 },
        { month: "Task 4", value: 91 },
      ],
      comments: [
        {
          id: 1,
          author: "You (Manager)",
          avatar: "https://picsum.photos/seed/3/32/32",
          text: "Great turnaround on Project X. We are back on track.",
          timestamp: "1d ago",
        },
      ],
    },
    {
      id: "mgr-4",
      title: "Team Member Churn",
      value: "2%",
      change: "-3%",
      changeType: "decrease",
      status: "on-track",
      description: "vs. last quarter",
      icon: "Users",
      chartType: "bar",
      trendData: [
        { month: "Q1", value: 5 },
        { month: "Q2", value: 4 },
        { month: "Q3", value: 2 },
      ],
      comments: [],
    },
  ],
  Employee: [
    {
      id: "emp-1",
      title: "Completed Tasks",
      value: "18",
      change: "-7",
      changeType: "decrease",
      status: "at-risk",
      description: "This month",
      icon: "Target",
      chartType: "bar",
      trendData: [
        { month: "Week 1", value: 7 },
        { month: "Week 2", value: 5 },
        { month: "Week 3", value: 4 },
        { month: "Week 4", value: 2 },
      ],
      comments: [
        {
          id: 1,
          author: "Manager",
          avatar: "https://picsum.photos/seed/3/32/32",
          text: "Let's sync up on your current workload.",
          timestamp: "1d ago",
        },
      ],
    },
    {
      id: "emp-2",
      title: "Code Commits",
      value: "135",
      change: "+15%",
      changeType: "increase",
      status: "on-track",
      description: "Last 30 days",
      icon: "TrendingUp",
      chartType: "line",
      trendData: [
        { month: "Week 1", value: 30 },
        { month: "Week 2", value: 35 },
        { month: "Week 3", value: 32 },
        { month: "Week 4", value: 38 },
      ],
      comments: [],
    },
    {
      id: "emp-3",
      title: "Active Sales Leads",
      value: "18",
      change: "+3",
      changeType: "increase",
      status: "on-track",
      description: "Target: 15",
      icon: "ShoppingCart",
      chartType: "bar",
      trendData: [
        { month: "Week 1", value: 12 },
        { month: "Week 2", value: 14 },
        { month: "Week 3", value: 16 },
        { month: "Week 4", value: 18 },
      ],
      comments: [
        {
          id: 1,
          author: "Manager",
          avatar: "https://picsum.photos/seed/3/32/32",
          text: "Fantastic work on prospecting this month!",
          timestamp: "2h ago",
        },
      ],
    },
  ],
};

export const notifications: Notification[] = [
  {
    id: "notif-1",
    kpiTitle: "Customer Acquisition Cost (CAC)",
    message: "KPI is now 'off-track'. Cost has increased by 12.5%.",
    timestamp: "5h ago",
    read: false,
  },
  {
    id: "notif-2",
    kpiTitle: "Average Ticket Resolution Time",
    message: "KPI is now 'off-track'. Time has increased by 24%.",
    timestamp: "1d ago",
    read: false,
  },
  {
    id: "notif-3",
    kpiTitle: "Annual Recurring Revenue (ARR)",
    message: "New comment from Alex G.",
    timestamp: "3h ago",
    read: true,
  },
];

export const user = {
    name: "Alex Denton",
    email: "alex.denton@insightboard.com",
    avatar: "https://picsum.photos/seed/1/32/32",
}
