import type { Kpi, Department } from "@/lib/types";

export const kpisByDepartment: Record<Department, Kpi[]> = {
  Marketing: [
    {
      id: "mkt-1",
      title: "New Clients Reached",
      value: "950",
      change: "-12%",
      changeType: "decrease",
      status: "at-risk",
      description: "vs. previous month",
      icon: "Users",
      chartType: "line",
      trendData: [
        { month: "Jan", value: 1100 },
        { month: "Feb", value: 1050 },
        { month: "Mar", value: 1000 },
        { month: "Apr", value: 980 },
        { month: "May", value: 960 },
        { month: "Jun", value: 950 },
      ],
      comments: [],
      roles: ["CEO", "Manager"],
    },
    {
      id: "mkt-2",
      title: "Demos Booked",
      value: "280",
      change: "+10%",
      changeType: "increase",
      status: "on-track",
      description: "vs. previous month",
      icon: "Presentation",
      chartType: "bar",
      trendData: [
        { month: "Jan", value: 200 },
        { month: "Feb", value: 210 },
        { month: "Mar", value: 230 },
        { month: "Apr", value: 250 },
        { month: "May", value: 260 },
        { month: "Jun", value: 280 },
      ],
      comments: [],
      roles: ["Manager", "Employee"],
    },
    {
      id: "mkt-3",
      title: "Campaigns Launched",
      value: "3",
      change: "-1",
      changeType: "decrease",
      status: "at-risk",
      description: "This quarter",
      icon: "Megaphone",
      chartType: "bar",
      trendData: [
        { month: "Q1", value: 4 },
        { month: "Q2", value: 3 },
      ],
      comments: [],
      roles: ["Manager", "Employee"],
    },
    {
      id: "mkt-4",
      title: "Conversion Rate",
      value: "3.5%",
      change: "-1.2%",
      changeType: "decrease",
      status: "off-track",
      description: "vs. previous month",
      icon: "Goal",
      chartType: "line",
      trendData: [
        { month: "Jan", value: 5.0 },
        { month: "Feb", value: 4.8 },
        { month: "Mar", value: 4.7 },
        { month: "Apr", value: 4.2 },
        { month: "May", value: 3.8 },
        { month: "Jun", value: 3.5 },
      ],
      comments: [],
      roles: ["CEO", "Manager"],
    },
    {
      id: "mkt-5",
      title: "Social Media Engagement",
      value: "15%",
      change: "+3%",
      changeType: "increase",
      status: "on-track",
      description: "vs. previous month",
      icon: "ThumbsUp",
      chartType: "line",
      trendData: [
        { month: "Jan", value: 10 },
        { month: "Feb", value: 11 },
        { month: "Mar", value: 12 },
        { month: "Apr", value: 13 },
        { month: "May", value: 14 },
        { month: "Jun", value: 15 },
      ],
      comments: [],
      roles: ["Employee"],
    },
  ],
  Engineering: [
    {
      id: "eng-1",
      title: "New Features Developed",
      value: "5",
      change: "-3",
      changeType: "decrease",
      status: "off-track",
      description: "This quarter",
      icon: "GitMerge",
      chartType: "bar",
      trendData: [
        { month: "Q1", value: 8 },
        { month: "Q2", value: 5 },
      ],
      comments: [],
      roles: ["CEO", "Manager"],
    },
    {
      id: "eng-2",
      title: "Bugs Fixed",
      value: "95",
      change: "-25%",
      changeType: "decrease",
      status: "at-risk",
      description: "vs. previous month",
      icon: "Bug",
      chartType: "bar",
      trendData: [
        { month: "Jan", value: 150 },
        { month: "Feb", value: 140 },
        { month: "Mar", value: 130 },
        { month: "Apr", value: 120 },
        { month: "May", value: 110 },
        { month: "Jun", value: 95 },
      ],
      comments: [],
      roles: ["Manager", "Employee"],
    },
    {
      id: "eng-3",
      title: "Tickets Closed",
      value: "280",
      change: "-10%",
      changeType: "decrease",
      status: "at-risk",
      description: "vs. previous month",
      icon: "FileCheck",
      chartType: "line",
      trendData: [
        { month: "Jan", value: 350 },
        { month: "Feb", value: 340 },
        { month: "Mar", value: 320 },
        { month: "Apr", value: 310 },
        { month: "May", value: 300 },
        { month: "Jun", value: 280 },
      ],
      comments: [],
      roles: ["Employee"],
    },
    {
      id: "eng-4",
      title: "Code Coverage",
      value: "82%",
      change: "-6%",
      changeType: "decrease",
      status: "off-track",
      description: "Project 'Phoenix'",
      icon: "Percent",
      chartType: "line",
      trendData: [
        { month: "Jan", value: 90 },
        { month: "Feb", value: 88 },
        { month: "Mar", value: 86 },
        { month: "Apr", value: 85 },
        { month: "May", value: 84 },
        { month: "Jun", value: 82 },
      ],
      comments: [],
      roles: ["Manager"],
    },
    {
      id: "eng-5",
      title: "Deployment Frequency",
      value: "8/month",
      change: "-4",
      changeType: "decrease",
      status: "at-risk",
      description: "Production environment",
      icon: "Rocket",
      chartType: "bar",
      trendData: [
        { month: "Jan", value: 12 },
        { month: "Feb", value: 12 },
        { month: "Mar", value: 10 },
        { month: "Apr", value: 10 },
        { month: "May", value: 9 },
        { month: "Jun", value: 8 },
      ],
      comments: [],
      roles: ["CEO", "Manager"],
    },
  ],
  Testing: [
    {
      id: "tst-1",
      title: "New Features Tested",
      value: "5",
      change: "-3",
      changeType: "decrease",
      status: "off-track",
      description: "This quarter",
      icon: "ListChecks",
      chartType: "bar",
      trendData: [
        { month: "Q1", value: 8 },
        { month: "Q2", value: 5 },
      ],
      comments: [],
      roles: ["Manager"],
    },
    {
      id: "tst-2",
      title: "Bugs Found",
      value: "68",
      change: "+26",
      changeType: "increase",
      status: "off-track",
      description: "vs. previous month (Critical: 15)",
      icon: "Search",
      chartType: "bar",
      trendData: [
        { month: "Jan", value: 35 },
        { month: "Feb", value: 38 },
        { month: "Mar", value: 42 },
        { month: "Apr", value: 55 },
        { month: "May", value: 60 },
        { month: "Jun", value: 68 },
      ],
      comments: [],
      roles: ["Manager", "Employee"],
    },
    {
      id: "tst-3",
      title: "Test Case Coverage",
      value: "98%",
      change: "+3%",
      changeType: "increase",
      status: "on-track",
      description: "End-to-end scenarios",
      icon: "ClipboardList",
      chartType: "line",
      trendData: [
        { month: "Jan", value: 92 },
        { month: "Feb", value: 93 },
        { month: "Mar", value: 94 },
        { month: "Apr", value: 95 },
        { month: "May", value: 96 },
        { month: "Jun", value: 98 },
      ],
      comments: [],
      roles: ["CEO", "Manager"],
    },
    {
      id: "tst-4",
      title: "Regression Issues",
      value: "8",
      change: "+5",
      changeType: "increase",
      status: "off-track",
      description: "Post-deployment",
      icon: "Flame",
      chartType: "bar",
      trendData: [
        { month: "Jan", value: 2 },
        { month: "Feb", value: 3 },
        { month: "Mar", value: 4 },
        { month: "Apr", value: 6 },
        { month: "May", value: 7 },
        { month: "Jun", value: 8 },
      ],
      comments: [],
      roles: ["Employee"],
    },
    {
      id: "tst-5",
      title: "Automation Success Rate",
      value: "96.5%",
      change: "-2%",
      changeType: "decrease",
      status: "at-risk",
      description: "Nightly builds",
      icon: "Repeat",
      chartType: "line",
      trendData: [
        { month: "Jan", value: 98.5 },
        { month: "Feb", value: 98.2 },
        { month: "Mar", value: 98.0 },
        { month: "Apr", value: 97.5 },
        { month: "May", value: 97.0 },
        { month: "Jun", value: 96.5 },
      ],
      comments: [],
      roles: ["CEO", "Manager"],
    },
  ],
};
